### ISSUE TITLE
请问转换后，spine导入打开后图片全部变形是怎么回事呀？

### ISSUE THREAD

**Issue by huahuacn** [zhong317/spriter2spine#1]
Spriter是R11。Spine是3.8.75。转换不报错，用spine打开后，所有的图片都变形了请问怎么解决呀？

**Comment by zhong317** [comment]
你好, 方便提供一下出问题的Spriter动画文件吗? 晚上我可以帮你看看, 你可以私发我的邮箱: zhong317@126.com. 如果不方便的话, 或者可以提供一些截图, 帮助我做判断.

**Comment by huahuacn** [comment]
你好，我已经将Spriter动画文件私发到你的邮箱啦。麻烦你帮忙看看，感谢~

**Comment by zhong317** [comment]
好的，已收到，晚上回去查下。不客气～

**Comment by huahuacn** [comment]
HI 老哥，不好意思，请问你有帮忙看一下吗？

**Comment by zhong317** [comment]
你好, 问题我大概查到了,  但今天刚好有点事, 还没时间去解决, 我争取明天帮你解决, 有耽误到的地方, 还请见谅.

**Comment by huahuacn** [comment]
谢谢谢谢，你太客气啦。

**Comment by huahuacn** [comment]
老哥~~~不好意思，请问啥时候有时间帮忙解决一下呀，感谢~~

**Comment by zhong317** [comment]
你好,  这个问题我这两天都在尝试解决,  比想象中困难, 进展比较缓慢, 明天我一整天都没空, 可能要后天才有机会继续搞, 目前问题大概解决了一半不到, 还有一些地方没想通, 主要原因是,  Spriter的骨骼层级缩放和Spine的处理方式不同, 导致无法找到简便的方法去把这些缩放信息转译成spine格式的数据,  只能做一些特殊处理, 以期取得等价的表现, 这部分处理比较复杂,  有些等价运算的细节我还没完全搞清楚.

**Comment by huahuacn** [comment]
感谢，麻烦了。。。

**Comment by zhong317** [comment]
你好, 问题已经大致fix了, 你可以更新最新的代码, 进行测试. 骨骼透明度那里可能还有点问题, 因为据我所知, spine不支持骨骼透明度, 而spriter支持, 这兼容起来非常麻烦, 所以目前我选择不去做兼容, 这可能会影响到你所提供的动画中bomb_lit_explode这个动作的表现效果, 会导致爆炸后, 人物主体没有隐身, 你可以在spine中通过手动微调修正, 工作量应该不是很大.

另外, 这次问题修正中其实还留了一个缺陷, 如果动画过程中进行了骨骼Scale值的变换, 可能还是会导致贴图错位, 这个问题解决起来相当麻烦, 由于时间关系, 这部分我也选择了暂时不修正. 幸运的是, 它不会影响到你所提供的动画, 所以你可以放心使用. 

最后, 表达一下歉意, 拖了将近一个周才帮你修正了相关问题, 实在抱歉! 这周家中有烦心事, 无法专心投入, 望见谅. 修改的有点仓促, 如果还有问题可随时联系我, 我尽量予与修正.

**Comment by huahuacn** [comment]
非常感谢，真的非常感谢。
我刚才对我拥有的多份spriter动画都进行了转换测试，都是OK的。骨骼透明度的问题不会有太大阻碍。
我很抱歉在你被烦恼缠身的时候依然要麻烦你，祝愿你早日解决烦心事。
再次表示感谢。给你添麻烦了。谢谢。

**Comment by zhong317** [comment]
不用客气，很高兴能帮助到你。老实说，之前我以为这玩意儿全世界只有我一个人用的上，没想到它还能帮到别人，我是挺惊喜的，你能使用它，对我而言也是一种鼓舞，所以我也非常感谢你，谢谢。
