### ISSUE TITLE
Bone position wrong !

### ISSUE THREAD

**Issue by antn9x** [zhong317/spriter2spine#2]
![image](https://user-images.githubusercontent.com/2052604/94717901-244fc380-037b-11eb-88aa-73092268adf3.png)
![image](https://user-images.githubusercontent.com/2052604/94718310-c96a9c00-037b-11eb-9816-a5d3bb53c424.png)

I used Spriter R9 and position was wrong, please can you help to check?

**Comment by zhong317** [comment]
Can you please to provide the  animation file to help me solve the problem？

**Comment by antn9x** [comment]
[Spriter_Parts.zip](https://github.com/zhong317/spriter2spine/files/5308999/Spriter_Parts.zip)
Here is my animation, please help to fix this. Thanks.

**Comment by zhong317** [comment]
You are welcome, let me take a look.

**Comment by zhong317** [comment]
Hi, antn9x. I have fixed the bug, please update the file to the latest version, and try again. Thank you very much for your feedback to help me improve my tools.

**Comment by antn9x** [comment]
Thank you, It work perfect now!
